<script lang="ts" module>
	import { tv, type VariantProps } from 'tailwind-variants';

	/**
	 * Reusable popover / dropdown-menu container.
	 *
	 * Open state is managed by the shared `popovers` store (so only one popover
	 * is open app-wide and outside-click / Escape closing is handled globally
	 * in +layout.svelte). Pass a unique `id` when you have several on screen.
	 *
	 * Usage:
	 *   <Popover id="post-menu" label="Post actions" triggerClass="...">
	 *     {#snippet trigger()}<Icon name="i-lucide-ellipsis" />{/snippet}
	 *     <MenuItem icon="i-lucide-link" onclick={...}>Copy link</MenuItem>
	 *     <MenuDivider />
	 *     <MenuItem tone="danger" icon="i-lucide-ban" onclick={...}>Block</MenuItem>
	 *   </Popover>
	 *
	 * `float` portals the panel to <body> with fixed coordinates measured from
	 * the trigger — for popovers that live inside scrollable/overflow panes
	 * (studio tool rail, inspector) where an absolutely-positioned panel would
	 * be clipped no matter its z-index.
	 */
	export const popoverPanel = tv({
		base: 'min-w-52 rounded-xl border border-[var(--ui-border-muted)] bg-[var(--surface-bg)] p-1.5 shadow-[var(--shadow-pop)]',
		variants: {
			placement: {
				'bottom-start': 'absolute z-30 top-full left-0 mt-1',
				'bottom-end': 'absolute z-30 top-full right-0 mt-1',
				'top-start': 'absolute z-30 bottom-full left-0 mb-1',
				'top-end': 'absolute z-30 bottom-full right-0 mb-1',
				// Floated variant: portaled to <body>, coordinates set inline.
				float: 'fixed z-[60]'
			},
			width: {
				auto: '',
				sm: 'w-52',
				md: 'w-56',
				lg: 'w-64'
			}
		},
		defaultVariants: { placement: 'bottom-end', width: 'md' }
	});

	export type PopoverVariants = VariantProps<typeof popoverPanel>;

	// SSR-safe counter for autogenerated popover ids.
	let fallbackId = 0;
	function nextFallbackId(): string {
		return `popover:${++fallbackId}`;
	}
</script>

<script lang="ts">
	import type { Snippet } from 'svelte';
	import { untrack } from 'svelte';
	import { popovers } from '$lib/stores/popovers.svelte';
	import { cn } from '$lib/utils/cn';

	let {
		id,
		placement = 'bottom-end',
		width = 'md',
		float = false,
		class: cls,
		rootClass = '',
		triggerClass = '',
		triggerActiveClass = '',
		label,
		trigger,
		children
	}: {
		id?: string;
		placement?: PopoverVariants['placement'];
		width?: PopoverVariants['width'];
		/** Portal the panel to <body> (fixed) — escapes scrollable ancestors. */
		float?: boolean;
		class?: string;
		rootClass?: string;
		triggerClass?: string;
		triggerActiveClass?: string;
		label?: string;
		trigger?: Snippet<[boolean]>;
		children?: Snippet;
	} = $props();

	// Popover identity is fixed at mount (the store keys open-state by it).
	const popoverId = untrack(() => id) ?? nextFallbackId();
	const open = $derived(popovers.isOpen(popoverId));
	const panelClass = $derived(
		float
			? popoverPanel({ placement: 'float', width, class: cls })
			: popoverPanel({ placement, width, class: cls })
	);

	function toggle(event: MouseEvent) {
		// Stop the global window click handler from immediately re-closing.
		event.stopPropagation();
		popovers.toggle(popoverId);
	}

	/** The app shell closes popovers from a window click handler. Panels must
	 * consume their own clicks first — especially floated panels, which are
	 * portaled to document.body and are no longer inside this component's root. */
	function keepPanelOpen(event: MouseEvent) {
		event.stopPropagation();
	}
	function stopPanelClicks(node: HTMLElement) {
		node.addEventListener('click', keepPanelOpen);
		return { destroy: () => node.removeEventListener('click', keepPanelOpen) };
	}

	// ---- floated panel positioning -------------------------------------------
	let triggerEl = $state<HTMLButtonElement | null>(null);
	let panelEl = $state<HTMLDivElement | null>(null);
	let pos = $state<{ top: number; left: number } | null>(null);

	/** Portal action — moves the panel to <body> so no ancestor clips it. */
	function portalToBody(node: HTMLElement) {
		document.body.appendChild(node);
		return {
			destroy: () => {
				node.remove();
			}
		};
	}

	$effect(() => {
		if (!open || !float) return;
		const trig = triggerEl;
		const panel = panelEl;
		if (!trig || !panel) return;

		const measure = () => {
			const r = trig.getBoundingClientRect();
			const pw = panel.offsetWidth || 208;
			const ph = panel.offsetHeight || 32;
			const gap = 4;
			const opensUp = placement === 'top-start' || placement === 'top-end';
			let top = opensUp ? r.top - ph - gap : r.bottom + gap;
			let left = placement === 'bottom-start' || placement === 'top-start' ? r.left : r.right - pw;
			// Keep the panel on screen (8px margins) — panels win over edges.
			left = Math.min(Math.max(8, left), Math.max(8, window.innerWidth - pw - 8));
			top = Math.min(
				Math.max(8, top),
				Math.max(8, window.innerHeight - Math.min(ph, window.innerHeight - 16) - 8)
			);
			pos = { top, left };
		};

		measure();
		// Content that grows after mount (lazy lists, GIF search) re-anchors.
		const ro = new ResizeObserver(measure);
		ro.observe(panel);
		return () => ro.disconnect();
	});
</script>

<div class={cn('relative inline-flex', rootClass)}>
	<button
		type="button"
		bind:this={triggerEl}
		onclick={toggle}
		class={cn('inline-flex items-center justify-center', triggerClass, open && triggerActiveClass)}
		aria-label={label}
		aria-expanded={open}
		aria-haspopup="menu"
	>
		{@render trigger?.(open)}
	</button>
	{#if open}
		{#if float}
			<div
				bind:this={panelEl}
				use:portalToBody
				use:stopPanelClicks
				data-popover-panel
				role="menu"
				class={panelClass}
				style={pos ? `top:${pos.top}px; left:${pos.left}px;` : 'visibility:hidden;'}
			>
				{@render children?.()}
			</div>
		{:else}
			<div use:stopPanelClicks data-popover-panel role="menu" class={panelClass}>
				{@render children?.()}
			</div>
		{/if}
	{/if}
</div>
