<script lang="ts" module>
	import { tv, type VariantProps } from 'tailwind-variants';

	/**
	 * Reusable popover / dropdown-menu container.
	 *
	 * Open state is managed by the shared `popovers` store (so only one popover
	 * is open app-wide and outside-click / Escape closing is handled globally
	 * in +layout.svelte). Pass a unique `id` when you have several on screen.
	 *
	 * Usage:
	 *   <Popover id="post-menu" label="Post actions" triggerClass="...">
	 *     {#snippet trigger()}<Icon name="i-lucide-ellipsis" />{/snippet}
	 *     <MenuItem icon="i-lucide-link" onclick={...}>Copy link</MenuItem>
	 *     <MenuDivider />
	 *     <MenuItem tone="danger" icon="i-lucide-ban" onclick={...}>Block</MenuItem>
	 *   </Popover>
	 */
	export const popoverPanel = tv({
		base: 'absolute z-30 min-w-52 rounded-xl border border-[var(--ui-border-muted)] bg-[var(--surface-bg)] p-1.5 shadow-[var(--shadow-pop)]',
		variants: {
			placement: {
				'bottom-start': 'top-full left-0 mt-1',
				'bottom-end': 'top-full right-0 mt-1',
				'top-start': 'bottom-full left-0 mb-1',
				'top-end': 'bottom-full right-0 mb-1'
			},
			width: {
				auto: '',
				sm: 'w-52',
				md: 'w-56',
				lg: 'w-64'
			}
		},
		defaultVariants: { placement: 'bottom-end', width: 'md' }
	});

	export type PopoverVariants = VariantProps<typeof popoverPanel>;

	// SSR-safe counter for autogenerated popover ids.
	let fallbackId = 0;
</script>

<script lang="ts">
	import type { Snippet } from 'svelte';
	import { untrack } from 'svelte';
	import { popovers } from '$lib/stores/popovers.svelte';
	import { cn } from '$lib/utils/cn';

	let {
		id,
		placement = 'bottom-end',
		width = 'md',
		class: cls,
		rootClass = '',
		triggerClass = '',
		triggerActiveClass = '',
		label,
		trigger,
		children
	}: {
		id?: string;
		placement?: PopoverVariants['placement'];
		width?: PopoverVariants['width'];
		class?: string;
		rootClass?: string;
		triggerClass?: string;
		triggerActiveClass?: string;
		label?: string;
		trigger?: Snippet;
		children?: Snippet;
	} = $props();

	// Popover identity is fixed at mount (the store keys open-state by it).
	const popoverId = untrack(() => id) ?? `popover:${fallbackId++}`;
	const open = $derived(popovers.isOpen(popoverId));
	const panelClass = $derived(popoverPanel({ placement, width, class: cls }));

	function toggle(event: MouseEvent) {
		// Stop the global window click handler from immediately re-closing.
		event.stopPropagation();
		popovers.toggle(popoverId);
	}
</script>

<div class={cn('relative inline-flex', rootClass)}>
	<button
		type="button"
		onclick={toggle}
		class={cn('inline-flex items-center justify-center', triggerClass, open && triggerActiveClass)}
		aria-label={label}
		aria-expanded={open}
		aria-haspopup="menu"
	>
		{@render trigger?.()}
	</button>
	{#if open}
		<div role="menu" class={panelClass}>
			{@render children?.()}
		</div>
	{/if}
</div>
